server.port: 8888
debug: true

spring:
  datasource:
    url: jdbc:h2:file:./data/h2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    pathmatch: # Workaround for Swagger bug.
      matching-strategy: ant_path_matcher
jwt:
  secret: 4800a5d0-e090-4f70-964a-ac5164dbf7e0
  expirationMs: 86400000 # 24 hours