server.port: 8888

spring:
  datasource:
    url: jdbc:h2:file:./data/h2
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  mvc:
    pathmatch: # Workaround for Swagger bug.
      matching-strategy: ant_path_matcher
  security:
    oauth2.resourceserver.jwt.issuer-uri: ${auth0.domain}

auth0.audience: http://qs.api
auth0.domain: https://dev-n5ogkgjf.eu.auth0.com/