name: Frontend

defaults:
  run:
    working-directory: frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:unit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npx vue-cli-service lint --no-fix
